/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GorgiasQuery
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-12T13:59:37.724Z")
public class GorgiasQuery {
  @SerializedName("facts")
  private List<String> facts = null;

  @SerializedName("gorgiasFiles")
  private List<String> gorgiasFiles = null;

  @SerializedName("query")
  private String query = null;

  @SerializedName("resultSize")
  private Integer resultSize = null;

  public GorgiasQuery facts(List<String> facts) {
    this.facts = facts;
    return this;
  }

  public GorgiasQuery addFactsItem(String factsItem) {
    if (this.facts == null) {
      this.facts = new ArrayList<String>();
    }
    this.facts.add(factsItem);
    return this;
  }

   /**
   * Get facts
   * @return facts
  **/
  @ApiModelProperty(value = "")
  public List<String> getFacts() {
    return facts;
  }

  public void setFacts(List<String> facts) {
    this.facts = facts;
  }

  public GorgiasQuery gorgiasFiles(List<String> gorgiasFiles) {
    this.gorgiasFiles = gorgiasFiles;
    return this;
  }

  public GorgiasQuery addGorgiasFilesItem(String gorgiasFilesItem) {
    if (this.gorgiasFiles == null) {
      this.gorgiasFiles = new ArrayList<String>();
    }
    this.gorgiasFiles.add(gorgiasFilesItem);
    return this;
  }

   /**
   * Get gorgiasFiles
   * @return gorgiasFiles
  **/
  @ApiModelProperty(value = "")
  public List<String> getGorgiasFiles() {
    return gorgiasFiles;
  }

  public void setGorgiasFiles(List<String> gorgiasFiles) {
    this.gorgiasFiles = gorgiasFiles;
  }

  public GorgiasQuery query(String query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @ApiModelProperty(value = "")
  public String getQuery() {
    return query;
  }

  public void setQuery(String query) {
    this.query = query;
  }

  public GorgiasQuery resultSize(Integer resultSize) {
    this.resultSize = resultSize;
    return this;
  }

   /**
   * Get resultSize
   * @return resultSize
  **/
  @ApiModelProperty(value = "")
  public Integer getResultSize() {
    return resultSize;
  }

  public void setResultSize(Integer resultSize) {
    this.resultSize = resultSize;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GorgiasQuery gorgiasQuery = (GorgiasQuery) o;
    return Objects.equals(this.facts, gorgiasQuery.facts) &&
        Objects.equals(this.gorgiasFiles, gorgiasQuery.gorgiasFiles) &&
        Objects.equals(this.query, gorgiasQuery.query) &&
        Objects.equals(this.resultSize, gorgiasQuery.resultSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(facts, gorgiasFiles, query, resultSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GorgiasQuery {\n");
    
    sb.append("    facts: ").append(toIndentedString(facts)).append("\n");
    sb.append("    gorgiasFiles: ").append(toIndentedString(gorgiasFiles)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    resultSize: ").append(toIndentedString(resultSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

