/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.QueryResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * GorgiasQueryResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-06-12T13:59:37.724Z")
public class GorgiasQueryResult {
  @SerializedName("errorMsg")
  private String errorMsg = null;

  @SerializedName("hasError")
  private Boolean hasError = null;

  @SerializedName("hasResult")
  private Boolean hasResult = null;

  @SerializedName("result")
  private List<QueryResult> result = null;

  public GorgiasQueryResult errorMsg(String errorMsg) {
    this.errorMsg = errorMsg;
    return this;
  }

   /**
   * Get errorMsg
   * @return errorMsg
  **/
  @ApiModelProperty(value = "")
  public String getErrorMsg() {
    return errorMsg;
  }

  public void setErrorMsg(String errorMsg) {
    this.errorMsg = errorMsg;
  }

  public GorgiasQueryResult hasError(Boolean hasError) {
    this.hasError = hasError;
    return this;
  }

   /**
   * Get hasError
   * @return hasError
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasError() {
    return hasError;
  }

  public void setHasError(Boolean hasError) {
    this.hasError = hasError;
  }

  public GorgiasQueryResult hasResult(Boolean hasResult) {
    this.hasResult = hasResult;
    return this;
  }

   /**
   * Get hasResult
   * @return hasResult
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasResult() {
    return hasResult;
  }

  public void setHasResult(Boolean hasResult) {
    this.hasResult = hasResult;
  }

  public GorgiasQueryResult result(List<QueryResult> result) {
    this.result = result;
    return this;
  }

  public GorgiasQueryResult addResultItem(QueryResult resultItem) {
    if (this.result == null) {
      this.result = new ArrayList<QueryResult>();
    }
    this.result.add(resultItem);
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public List<QueryResult> getResult() {
    return result;
  }

  public void setResult(List<QueryResult> result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GorgiasQueryResult gorgiasQueryResult = (GorgiasQueryResult) o;
    return Objects.equals(this.errorMsg, gorgiasQueryResult.errorMsg) &&
        Objects.equals(this.hasError, gorgiasQueryResult.hasError) &&
        Objects.equals(this.hasResult, gorgiasQueryResult.hasResult) &&
        Objects.equals(this.result, gorgiasQueryResult.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorMsg, hasError, hasResult, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GorgiasQueryResult {\n");
    
    sb.append("    errorMsg: ").append(toIndentedString(errorMsg)).append("\n");
    sb.append("    hasError: ").append(toIndentedString(hasError)).append("\n");
    sb.append("    hasResult: ").append(toIndentedString(hasResult)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

