/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.GorgiasQuery;
import io.swagger.client.model.GorgiasQueryResult;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ExecuteGorgiasQueryControllerApi {
    private ApiClient apiClient;

    public ExecuteGorgiasQueryControllerApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ExecuteGorgiasQueryControllerApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for executeQueryUsingPOST
     * @param gorgiasQuery gorgiasQuery (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call executeQueryUsingPOSTCall(GorgiasQuery gorgiasQuery, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = gorgiasQuery;

        // create path and map variables
        String localVarPath = "/GorgiasQuery";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call executeQueryUsingPOSTValidateBeforeCall(GorgiasQuery gorgiasQuery, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'gorgiasQuery' is set
        if (gorgiasQuery == null) {
            throw new ApiException("Missing the required parameter 'gorgiasQuery' when calling executeQueryUsingPOST(Async)");
        }
        

        com.squareup.okhttp.Call call = executeQueryUsingPOSTCall(gorgiasQuery, progressListener, progressRequestListener);
        return call;

    }

    /**
     * executeQuery
     * 
     * @param gorgiasQuery gorgiasQuery (required)
     * @return GorgiasQueryResult
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public GorgiasQueryResult executeQueryUsingPOST(GorgiasQuery gorgiasQuery) throws ApiException {
        ApiResponse<GorgiasQueryResult> resp = executeQueryUsingPOSTWithHttpInfo(gorgiasQuery);
        return resp.getData();
    }

    /**
     * executeQuery
     * 
     * @param gorgiasQuery gorgiasQuery (required)
     * @return ApiResponse&lt;GorgiasQueryResult&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<GorgiasQueryResult> executeQueryUsingPOSTWithHttpInfo(GorgiasQuery gorgiasQuery) throws ApiException {
        com.squareup.okhttp.Call call = executeQueryUsingPOSTValidateBeforeCall(gorgiasQuery, null, null);
        Type localVarReturnType = new TypeToken<GorgiasQueryResult>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * executeQuery (asynchronously)
     * 
     * @param gorgiasQuery gorgiasQuery (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call executeQueryUsingPOSTAsync(GorgiasQuery gorgiasQuery, final ApiCallback<GorgiasQueryResult> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = executeQueryUsingPOSTValidateBeforeCall(gorgiasQuery, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<GorgiasQueryResult>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
