# camunda.bpm:
#   webapp:
#     index-redirect-enabled: true
#   admin-user:
#     id: admin
#     password: demo
#     firstName: Demo
#   filter:
#     create: All tasks
server:
  port: 8080
  servlet:
    context-path: /
# camunda:
#   bpm:
#     deployment-resource-pattern: classpath*:**/*.bpmn


logging:
  level:
    org.camunda: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
gorgias:
  api:
    username: ${GORGIAS_USER}
    password: ${GORGIAS_PASS}
    basepath: http://aiasvm1.amcl.tuc.gr:8085